name: clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  dev: ^1.0.0
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  hive: ^2.2.3
  internet_connection_checker_plus: ^2.2.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.4
  mocktail: ^1.0.3
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"
  min_sdk_android: 21
flutter:
  uses-material-design: true
  fonts:
    - family: concert_one
      fonts:
        - asset: assets/fonts/concert_one.ttf
          weight: 400
